apiVersion: apps/v1
kind: Deployment
metadata:
  name: m-scheduler-extender
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m-scheduler-extender
  template:
    metadata:
      labels:
        app: m-scheduler-extender
    spec:
      serviceAccountName: m-scheduler-extender
      containers:
        - name: extender
          image: ccr.ccs.tencentyun.com/mervynwang/m-scheduler-extender:v1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8010
            - name: https
              containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: m-scheduler-extender
  namespace: default
spec:
  selector:
    app: m-scheduler-extender
  ports:
    - name: http
      protocol: TCP
      port: 8010
      targetPort: 8010
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443