# FILEPATH:/Users/yangyang/go/src/github.com/github-wyy/m-scheduler-extender/deploy/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: m-scheduler-extender
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: m-scheduler-extender
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: m-scheduler-extender
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: m-scheduler-extender
subjects:
  - kind: ServiceAccount
    name: m-scheduler-extender
    namespace: default
